language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: dragons-with-backpacks
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: dtJ5HPBH8RJ90kXHHawPPcsNaUk8G+l6+FCYWKech1Oa6cTQYXJzsazUz4BZrP5Wr+Lb3qGbkBK7hN1tE6n/GETILWDELiLokFjnLi4vJz3RoHuNyqEKCT21UDLJAnW9PxMOfqDSx4vREgnaBTaNdPMaNzse/MgoP+ouWjAXkuaPGsgvWNq8jDYqcO1kncyO5JdvdPFgdZ4rlNN1ow2/IcDihGtgZZlIPa8bK7Xdfrb1wHK1ePRJ/96RHteeaUKxwT60S5ajzZj5D3BeJXs3fKjpLyy9rNW2ruLAxJNQUfwXjnHDkif/wLHOyfYVDaN3VOF83dUO9KwP4gBkuQUGBn76VLl+TaYo0tYS07sEZsefhTEfVdfCBDbP16G2FzVrJG1Qh0EEHntv+efH5oLbo2zk6c4CrnX0SWac/mViakUDhU9kRVFvvnq67fKyQaWWu1/W7HTSCNVBskzv8vFBphv621XoUUs5ocmkYWE9jojT+RX3tgm+KFRO1BTjmt/RzCSjA7ZtDDoRBcABWPqqwIE4/RSieGQKJHbK1o66xi10rdhq4iNKqrlPJk2Ni0S+Q+BzK25vJcVUDVg/MHRbIic8cZJdBdP3FhHJQQ9b6+2Gn9TXpxIojMEksb/XBbxs/pAOmc3R4BTEGIbOu+m/Ly4K6QY1MQfFN62ppgEFRF4=
